# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package to NPM

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: github.event.release.target_commitish == 'main' # Only run this workflow if the release is created from the main branch
    uses: vestfoldfylke/shared/.github/workflows/publish-npm-package.yml@main
    